### User sign up endpoint
POST http://localhost:3001/v1/user
Content-Type: application/json

{
    "name":"Julia Dannerth",
    "company": "Company name",
    "address": "Some address",
    "phone": "1234567891",
    "email": "123@123.com",
    "password": "secret123"
}

### User sign in endpoint
POST http://localhost:3001/v1/user/login
Content-Type: application/json

{
    "email": "123@123.com",
    "password": "secret123"
}

### Get a user profile endpoint
GET  http://localhost:3001/v1/user
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImUyQGUuY29tIiwiaWF0IjoxNjA0OTY1NzY5LCJleHAiOjE2MDQ5NjY2Njl9.F2-7KZCO2XGZorvh8XubGib1KGZAmfvbtD1_4jLZtH0

{
    "email": "123@123.com",
    "password": "secret123"
}

###Token routers

##Get refreshed token
GET http://localhost:3001/v1/tokens
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImUyQGUuY29tIiwiaWF0IjoxNjA0OTcwODY5LCJleHAiOjE2MDc1NjI4Njl9.n798jpZ8w9MeEpvU8QvHBFq8TAbEZRWHSFpWXaB5_iE
